### ISSUE TITLE
XHR list container can get screwed by styles on the injected page

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/interceptor#18]
The XHR list by default looks like this : 
![image](https://cloud.githubusercontent.com/assets/1707078/15157297/98b07972-1708-11e6-9036-2ed92f0d54ee.png)

But the page can have styles that can change how the container looks, For example:
![image](https://cloud.githubusercontent.com/assets/1707078/15157321/bb0f4570-1708-11e6-9e9f-71365a7a4ee7.png)

Maybe we can use a minimal CSS modal library and render an iframe inside the modal to ensure styles aren't leaked in ? @iffyuva

**Comment by amit-mb** [comment]
Closing this as the issue doesn't exists after UI redesign. PR : https://github.com/code-mancers/interceptor/pull/33
