### ISSUE TITLE
Intercept button that sends a mock response code (5)

### ISSUE THREAD

**Issue by amit-mb** [code-mancers/interceptor#25]

**Comment by amit-mb** [comment]
Add ability to intercept error status codes which shows a input field where the error status code is input and a button which mocks the said error code

**Comment by revathskumar** [comment]
This is in Done since the basic sinon setup for the interceptor is done.
Need to add the ability for the status code.

**Comment by revathskumar** [comment]
The editing the status code will be tracked in #37. Hence closing this.
