### ISSUE TITLE
Ability to watch for XHR requests using URL pattern

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/interceptor#5]
A user should be able to type in a [URL match pattern](https://developer.chrome.com/extensions/match_patterns) into a textbox inside the popup. From now on, only requests to matching URLs should be listened to.

**Comment by amit-mb** [comment]
Closing this as the fuzzy search already filters the `URL patterns` inside the textbox and lists only those which match. [This](https://github.com/kentcdodds/match-sorter) library makes it possible. Although the extension continues to listen to all incoming requests for that particular tab.
